# Setup
name:         GustavHansen's magnificent blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
baseproject:  "SocialDataAssignment2"
url:          "https://gustavhansen99.github.io/SocialDataAssignment2"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
